### ISSUE TITLE
Create new XFCE applications menu

### ISSUE THREAD

**Issue by THS-on** [imedias/lernstick-menu-xdg#3]
The current menu doesn't use the new lernstick.merge.menu, doesn't show the education software and has some icon issues.

# TODO
 * [ ] Create a basic new config
 * [ ] use lernstick.merge.menu if possible
 * [ ] fix missing icons in the menu (might require to change the icon theme)
